### ISSUE TITLE
Unclear user approval page

### ISSUE THREAD

**Issue by robertsteilberg** [mVax-app/mVax#14]
If there are no user requests in the approve users page, there should be some indication of that because during testing, users have been confused by the blankness of the page. Would not be a foreseeable problem for main users for the app but helps with ease of use of app and is an easy fix.

Acceptance criteria: Text on screen when there are no user requests that informs the administrator of such.

**Comment by robertsteilberg** [comment]
I think in general the UI for this page needs to be made more intuitive and cleaner.

**Comment by tribby5** [comment]
Pulls that fulfill this work:
https://github.com/mVax-app/mVax/pull/71
https://github.com/mVax-app/mVax/pull/72

Completed work: Now when the ListView on ApproveUsersFragment is empty, the ListView is set to show "No user requests" which addresses the first step of this issue. Additionally, the UI has been more intuitive and simpler overall to address Rob's comment. Instead of having a screen that you must click to take you to a modal, there are now check and deny buttons clearly defined for each user request making the process more streamlined. Additionally, there are instructions for the page and a help button that describes user roles in case the administer forgot
