### ISSUE TITLE
User approval page UI

### ISSUE THREAD

**Issue by robertsteilberg** [mVax-app/mVax#15]
When a user presses the back button when they are on the ApproveUsersFragment, there is a `FragmentTransaction` error when the current UI is overlaid over the new screen. Reason for this bug is improper/buggy use of a fragment transaction--talk to Rob if you have issues resolving this, he's done a lot with buggy fragment transactions.

Additionally, occasionally, when keyboard is up the top of the screen is cut off for an unknown reason.

The UI in general for the user approval page needs cleaning up.

**Comment by tribby5** [comment]
This issue was fixed in a previous pull that I did (not certain of the number). Essentially the problem was that the Fragment was not added to the backstack. I have tested the application 10 different times going in and out of every possible screen/fragment that I could see and it never once had the overlaying problem. The other UI problems mentioned in this issue were fixed in another issue which was already closed.
