### ISSUE TITLE
PDF design pattern

### ISSUE THREAD

**Issue by robertsteilberg** [mVax-app/mVax#3]
mVax is currently targeted to filling in the specific Honduras Ministry of Health forms. However, with a simple interface added over the top, would be possible to make the design much better. Reflection could also be used to remove repetitive code when selecting which PDF to build.

**Comment by tribby5** [comment]
Chose not to do a design pattern for PDF creation because all the pdfs had different requirements unlike previously thought. Before, it was thought that most if not all of the pdfs were based around a single day but following Steven's trip to Honduras we realized that was not the case. Instead of a design pattern on pdf creation, there was a inheritance hierarchy based around fetching the actual vaccination records from FB.
